lang: ruby
before_install: gem install bundler --pre
install:
  - gem update --system
  - bundle update
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - rbx-18mode
  - jruby-19mode
branches:
  only:
    - master
